from . import tests_forms_funcionario
from . import tests_forms_paciente
from . import tests_models_atendimento
from . import tests_models_chamada
from . import tests_models_customuser
from . import tests_models_guiche
from . import tests_models_paciente
from . import tests_models_registro
from . import tests_utils
