# Generated by Django 5.2.7 on 2025-11-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_paciente_telefone_celular"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, verbose_name="Tentativas de login falhadas"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lockout_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bloqueado até"
            ),
        ),
    ]
