# Generated by Django 5.2.11 on 2026-04-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_chamada_desistencia_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamada",
            name="acao",
            field=models.CharField(
                choices=[
                    ("chamada", "Chamada"),
                    ("reanuncio", "Reanúncio"),
                    ("confirmado", "Confirmado"),
                    ("desistencia", "Desistência"),
                ],
                max_length=15,
            ),
        ),
    ]
